name: zohobooks_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  oauth2: ^2.0.3 
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
  mockito: ^5.4.4
  dartvcr: ^0.3.0
  faker: ^2.2.0
